/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-south-1",
    "aws_cognito_identity_pool_id": "ap-south-1:f633210f-56df-44db-9989-4befc6d0dc33",
    "aws_cognito_region": "ap-south-1",
    "aws_user_pools_id": "ap-south-1_QYHsmF7Wf",
    "aws_user_pools_web_client_id": "2s4lf45ubhf0jf3s1n1p6ie79l",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://hwrpzayd4vgghofoetiwr3eweq.appsync-api.ap-south-1.amazonaws.com/graphql",
    "aws_appsync_region": "ap-south-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
